//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customers
    {    // Préciser la clé primère et l'auto incrmenter  (normalement ca n'a pas de sens cause deja fait dans labase sql)  DbFirst!!!
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CustomerId { get; set; }

        [Display( Name= "Customer Name" )]
        [Required(ErrorMessage ="Erreur : le nom est obligatoire!!")]
        public string FirstName { get; set; }

        [Display(Name = "TEST")]
        [Required(ErrorMessage = "Erreur : le prénom est obligatoire!!")]
        public string LastName { get; set; }

        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Invoice { get; set; }
        public string CustomerOpinion { get; set; }

    }
}
